version: '3.8'

services:
  backend:
    build:
      context: ./jobber-be
    ports:
      - "8000:8000"
    env_file:
      - ./jobber-be/.env

  frontend:
    build:
      context: ./jobber-ui
    ports:
      - "5173:80"